version: '3'

services:
  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    command: bach -c "python manage.py collectstatic && manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
  celery:
    build: .
    command: celery -A core worker -B
    volumes:
      - .:/code
    links:
      - redis
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./.data/mysql:/var/lib/mysql
