# Generated by Django 2.2 on 2020-02-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_performance_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='video',
            field=models.ManyToManyField(related_name='tags', to='app.Video'),
        ),
    ]
