# Generated by Django 2.2 on 2020-03-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200229_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='chan_id',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='tag',
            name='video',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='app.Video'),
        ),
    ]
