# Generated by Django 2.2 on 2020-03-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200301_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', related_query_name='performance', to='app.Video'),
        ),
    ]
